const galleries = {"lijing": {"cover": "assets/stays/lijing/cover.jpg", "day": ["assets/stays/lijing/day-1.jpg", "assets/stays/lijing/day-2.jpg", "assets/stays/lijing/day-3.jpg", "assets/stays/lijing/day-4.jpg", "assets/stays/lijing/day-5.jpg", "assets/stays/lijing/day-6.jpg", "assets/stays/lijing/day-7.jpg"], "night": ["assets/stays/lijing/night-1.jpg", "assets/stays/lijing/night-2.jpg", "assets/stays/lijing/night-3.jpg", "assets/stays/lijing/night-4.jpg"], "rooms": ["assets/stays/lijing/room-1.jpg", "assets/stays/lijing/room-2.jpg", "assets/stays/lijing/room-3.jpg", "assets/stays/lijing/room-4.jpg"]}, "orange": {"cover": "assets/stays/orange/cover.jpg", "day": ["assets/stays/orange/day-1.jpg", "assets/stays/orange/day-2.jpg", "assets/stays/orange/day-3.jpg", "assets/stays/orange/day-4.jpg", "assets/stays/orange/day-5.jpg", "assets/stays/orange/day-6.jpg", "assets/stays/orange/day-7.jpg", "assets/stays/orange/day-8.jpg", "assets/stays/orange/day-9.jpg"], "night": ["assets/stays/orange/night-1.jpg", "assets/stays/orange/night-2.jpg", "assets/stays/orange/night-3.jpg"], "rooms": ["assets/stays/orange/room-1.jpg", "assets/stays/orange/room-2.jpg", "assets/stays/orange/room-3.jpg", "assets/stays/orange/room-4.jpg"]}, "shepherd": {"cover": "assets/stays/shepherd/cover.jpg", "day": ["assets/stays/shepherd/day-1.jpg", "assets/stays/shepherd/day-2.jpg", "assets/stays/shepherd/day-3.jpg", "assets/stays/shepherd/day-4.jpg", "assets/stays/shepherd/day-5.jpg", "assets/stays/shepherd/day-6.jpg", "assets/stays/shepherd/day-7.jpg", "assets/stays/shepherd/day-8.jpg"], "night": ["assets/stays/shepherd/night-1.jpg", "assets/stays/shepherd/night-2.jpg"], "rooms": ["assets/stays/shepherd/room-1.jpg", "assets/stays/shepherd/room-2.jpg", "assets/stays/shepherd/room-3.jpg", "assets/stays/shepherd/room-4.jpg"]}, "dongmen": {"cover": "assets/stays/dongmen/cover.jpg", "day": ["assets/stays/dongmen/day-1.jpg", "assets/stays/dongmen/day-2.jpg", "assets/stays/dongmen/day-3.jpg", "assets/stays/dongmen/day-4.jpg", "assets/stays/dongmen/day-5.jpg", "assets/stays/dongmen/day-6.jpg", "assets/stays/dongmen/day-7.jpg"], "night": [], "rooms": ["assets/stays/dongmen/room-1.jpg", "assets/stays/dongmen/room-2.jpg", "assets/stays/dongmen/room-3.jpg", "assets/stays/dongmen/room-4.jpg"]}, "beimen": {"cover": "assets/stays/beimen/cover.jpg", "day": ["assets/stays/beimen/day-1.jpg", "assets/stays/beimen/day-2.jpg", "assets/stays/beimen/day-3.jpg", "assets/stays/beimen/day-4.jpg", "assets/stays/beimen/day-5.jpg", "assets/stays/beimen/day-6.jpg", "assets/stays/beimen/day-7.jpg", "assets/stays/beimen/day-8.jpg", "assets/stays/beimen/day-9.jpg"], "night": ["assets/stays/beimen/night-1.jpg", "assets/stays/beimen/night-2.jpg", "assets/stays/beimen/night-3.jpg"], "rooms": ["assets/stays/beimen/room-1.jpg", "assets/stays/beimen/room-2.jpg", "assets/stays/beimen/room-3.jpg", "assets/stays/beimen/room-4.jpg"]}};

const stays = [
  {slug:"lijing",no:"一館",name:"麗景小木屋",label:"可包棟・可單房",capacity:"50 人",room:"雙人房、四人房、六人房",address:"屏東縣恆春鎮德和里坪頂路230號",deposit:"$10000（退房時確認無蓄意破壞、室內抽菸等行徑，會全額退還的唷~）",checkin:"下午3點 ( After 3 PM )",checkout:"上午11:00 ( Before 11 AM )  ※ 如需要加時間請提前告知 ※ ",extra:"☑ 平日$800/人、連續假日$1000/人",facilities:"KTV歡唱(至11PM), WiFi網路, 含停車位, 寵物可詢問, 泳池, 烤肉區, 麻將",high:"2 人  ⭢  平日(含週日)  $2000  、假日 $2800\n4 人  ⭢  平日(含週日)  $2800  、假日 $3800\n6 人  ⭢  平日(含週日)  $3800  、假日 $4800\n包棟  ⭢ 平日(含週日)  $36000、假日 $46000",low:"2 人  ⭢  平日(含週日)  $1500   、假日 $2000\n4 人  ⭢  平日(含週日)  $2000  、假日 $2800\n6 人  ⭢  平日(含週日)  $3000  、假日 $3800\n包棟  ⭢ 平日(含週日)  $35000、假日 $42000",bookingDeposit:"訂房價格的50%（完成匯款後才算保留房間）",note:"以上報價不適用於春節、音樂祭、特殊節日。\n農曆春節、特殊假日及連假期間：價格另計。"},
  {slug:"shepherd",no:"二館",name:"牧羊人 Villa民宿",label:"包棟民宿",capacity:"22 人",room:"雙人房 ×5、四人房 ×3",address:"屏東縣恆春鎮德和里德和路415巷25號",deposit:"$10000（退房時確認無蓄意破壞、室內抽菸等行徑，會全額退還的唷~）",checkin:"下午3點 (After 3 PM)",checkout:"上午11:00 (Before 11 AM)  ※ 如需要加時間請提前告知 ※ ",extra:"☑ 平日$800/人、連續假日$1000/人",facilities:"KTV歡唱(無限時), WiFi網路, 含停車位, 寵物可詢問, 泳池, 烤肉區, 麻將",high:"平日(含週日)  $19999、週五 $21999、週六 $25999",low:"平日(含週日)  $15999、週五 $17999、週六 $19999",bookingDeposit:"訂房價格的50%（完成匯款後才算保留房間）",note:"以上報價不適用於春節、音樂祭、特殊節日。\n農曆春節、特殊假日及連假期間：價格另計。"},
  {slug:"orange",no:"三館",name:"橘日民宿",label:"包棟民宿",capacity:"16 人",room:"雙人房 ×2、四人房 ×4",address:"當天入住之房客，請先與民宿管家聯繫取得地址唷~",deposit:"$10000（退房時確認無蓄意破壞、室內抽菸等行徑，會全額退還的唷~）",checkin:"下午3點 (After 3 PM)",checkout:"上午11:00 (Before 11 AM)  ※ 如需要加時間請提前告知 ※ ",extra:"☑ 平日$800/人、連續假日$1000/人",facilities:"KTV歡唱(至10:30PM), WiFi網路, 含停車位, 寵物可詢問, 泳池, 烤肉區, 麻將",high:"平日(含週日) $15999、週五 $19999、週六 $23999",low:"平日(含週日)  $14999、週五 $15999、週六 $17999",bookingDeposit:"訂房價格的50%（完成匯款後才算保留房間）",note:"以上報價不適用於春節、音樂祭、特殊節日。\n農曆春節、特殊假日及連假期間：價格另計。"},
  {slug:"beimen",no:"四館",name:"北門民宿☆新民宿☆",label:"包棟民宿",capacity:"26 人",room:"雙人房 ×5、四人房 ×4",address:"當天入住之房客，請先與民宿管家聯繫取得地址唷~",deposit:"$15000（退房時確認無蓄意破壞、室內抽菸等行徑，會全額退還的唷~）",checkin:"下午3點 (After 3 PM)",checkout:"上午11:00 (Before 11 AM)  ※ 如需要加時間請提前告知 ※ ",extra:"☑ 平日$800/人、連續假日$1000/人",facilities:"KTV歡唱(無限時), WiFi網路, 含停車位, 寵物可詢問, 泳池, 烤肉區, 麻將",high:"平日(含週日) $32000、週五 $36000、週六 $38000",low:"平日(含週日)  $26000、週五 $28000、週六 $32000",bookingDeposit:"訂房價格的50%（完成匯款後才算保留房間）",note:"以上報價不適用於春節、音樂祭、特殊節日。\n農曆春節、特殊假日及連假期間：價格另計。"},
  {slug:"dongmen",no:"五館",name:"東門民宿",label:"包棟民宿",capacity:"26 人",room:"露營車(雙人) ×3、四人房 ×3、八人房 ×1",address:"當天入住之房客，請先與民宿管家聯繫取得地址唷~",deposit:"$10000（退房時確認無蓄意破壞、室內抽菸等行徑，會全額退還的唷~）",checkin:"下午3點 (After 3 PM)",checkout:"上午11:00 (Before 11 AM)  ※ 如需要加時間請提前告知 ※ ",extra:"☑ 平日$800/人、連續假日$1000/人",facilities:"KTV歡唱(無限時), WiFi網路, 含停車位, 寵物可詢問, 泳池, 烤肉區, 麻將",high:"平日(含週日)  $19999、週五 $23999、週六 $27999",low:"平日(含週日)  $17999、週五 $18999、週六 $21999",bookingDeposit:"訂房價格的50%（完成匯款後才算保留房間）",note:"以上報價不適用於春節、音樂祭、特殊節日。\n農曆春節、特殊假日及連假期間：價格另計。"}
];

const esc=s=>String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const grid=document.querySelector("#stayGrid"),compare=document.querySelector("#compareBody"),modal=document.querySelector("#stayModal"),modalContent=document.querySelector("#modalContent");
const formatPrice=(value,slug="")=>{
  const safe=esc(value);
  return slug==="lijing" ? safe : safe.replaceAll("、","\n");
};
const lightbox=document.querySelector("#lightbox"),lightboxImage=document.querySelector("#lightboxImage"),lightboxCaption=document.querySelector("#lightboxCaption");
let activeImages=[],activeImageIndex=0;

const photoTotal=s=>1+galleries[s.slug].day.length+galleries[s.slug].night.length+galleries[s.slug].rooms.length;
grid.innerHTML=stays.map((s,i)=>`<article class="stay-card"><div class="stay-visual"><img src="${galleries[s.slug].cover}" alt="${esc(s.name)}封面照片" loading="lazy"><span class="stay-no">${esc(s.no)}</span><span class="photo-count">${photoTotal(s)} 張照片</span></div><div class="stay-content"><h3>${esc(s.name)}</h3><p class="stay-type">${esc(s.label)}</p><div class="stay-facts"><div class="fact"><small>包棟人數</small><strong>${esc(s.capacity)}</strong></div><div class="fact"><small>入住時間</small><strong>${esc(s.checkin.split("(")[0].trim())}</strong></div></div><p class="stay-room">${esc(s.room)}</p><button class="card-button" data-index="${i}">查看完整介紹與相簿</button></div></article>`).join("");
compare.innerHTML=stays.map(s=>`<tr><td><strong>${esc(s.no)}｜${esc(s.name)}</strong><br><small>${esc(s.label)}</small></td><td>${esc(s.capacity)}${s.no==="一館"?" (可單房／包棟)":""}</td><td>${esc(s.room)}</td><td class="price-block">${formatPrice(s.high,s.slug)}</td><td class="price-block">${formatPrice(s.low,s.slug)}</td></tr>`).join("");

function galleryBlock(title,images,s){
  if(!images.length)return "";
  return `<section class="gallery-section"><h3>${title}</h3><div class="gallery-grid">${images.map((src,i)=>`<button class="gallery-item" data-gallery-src="${src}" data-gallery-caption="${esc(s.name)}｜${title} ${i+1}"><img src="${src}" alt="${esc(s.name)}${title}照片 ${i+1}" loading="lazy"></button>`).join("")}</div></section>`;
}
function openModal(s){
  const g=galleries[s.slug],features=s.facilities.split(",").map(x=>`<span>${esc(x.trim())}</span>`).join("");
  modalContent.innerHTML=`<div class="modal-hero"><img src="${g.cover}" alt="${esc(s.name)}封面"><div class="modal-hero-copy"><p>${esc(s.no)}｜${esc(s.label)}</p><h2>${esc(s.name)}</h2></div></div><div class="modal-prices"><div class="season"><h4>旺季【6~9月】</h4><p>${formatPrice(s.high,s.slug)}</p></div><div class="season"><h4>淡季【10~5月】</h4><p>${formatPrice(s.low,s.slug)}</p></div></div><div class="modal-note">${esc(s.note)}</div><div class="modal-grid"><div class="detail-box"><h4>房型</h4><p>${esc(s.room)}</p></div><div class="detail-box"><h4>加床服務</h4><p>${esc(s.extra)}</p></div><div class="detail-box wide"><h4>地址</h4><p>${esc(s.address)}</p></div><div class="detail-box"><h4>入住時間</h4><p>${esc(s.checkin)}</p></div><div class="detail-box"><h4>退房時間</h4><p>${esc(s.checkout)}</p></div><div class="detail-box wide"><h4>入住押金</h4><p>${esc(s.deposit)}</p></div><div class="detail-box wide"><h4>訂房訂金</h4><p>${esc(s.bookingDeposit)}</p></div><div class="detail-box wide"><h4>設施</h4><div class="feature-list">${features}</div></div><div class="detail-box wide"><h4>聯絡方式</h4><p>Line ID：tina2001128 ｜IG：xav.yi_</p></div></div>${galleryBlock("公共區域｜白天",g.day,s)}${galleryBlock("公共區域｜夜景",g.night,s)}${galleryBlock("房間照片",g.rooms,s)}`;
  modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.classList.add("locked");modal.querySelector(".modal-panel").scrollTop=0;
}
function closeModal(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true");document.body.classList.remove("locked")}
function openLightbox(src,caption){
  activeImages=[...modalContent.querySelectorAll("[data-gallery-src]")].map(x=>({src:x.dataset.gallerySrc,caption:x.dataset.galleryCaption}));
  activeImageIndex=Math.max(0,activeImages.findIndex(x=>x.src===src));renderLightbox();lightbox.classList.add("open");lightbox.setAttribute("aria-hidden","false");
}
function renderLightbox(){const item=activeImages[activeImageIndex];if(!item)return;lightboxImage.src=item.src;lightboxImage.alt=item.caption;lightboxCaption.textContent=`${item.caption}（${activeImageIndex+1}/${activeImages.length}）`}
function closeLightbox(){lightbox.classList.remove("open");lightbox.setAttribute("aria-hidden","true")}
function shiftLightbox(step){activeImageIndex=(activeImageIndex+step+activeImages.length)%activeImages.length;renderLightbox()}
document.addEventListener("click",e=>{const card=e.target.closest("[data-index]");if(card)openModal(stays[Number(card.dataset.index)]);if(e.target.closest("[data-close-modal]"))closeModal();const photo=e.target.closest("[data-gallery-src]");if(photo)openLightbox(photo.dataset.gallerySrc,photo.dataset.galleryCaption);if(e.target.closest("[data-close-lightbox]"))closeLightbox();if(e.target.closest("[data-lightbox-prev]"))shiftLightbox(-1);if(e.target.closest("[data-lightbox-next]"))shiftLightbox(1)});
document.addEventListener("keydown",e=>{if(e.key==="Escape"){if(lightbox.classList.contains("open"))closeLightbox();else closeModal()}if(lightbox.classList.contains("open")&&e.key==="ArrowLeft")shiftLightbox(-1);if(lightbox.classList.contains("open")&&e.key==="ArrowRight")shiftLightbox(1)});
const toggle=document.querySelector(".menu-toggle"),nav=document.querySelector(".main-nav");toggle.addEventListener("click",()=>{const open=nav.classList.toggle("open");toggle.setAttribute("aria-expanded",String(open))});nav.addEventListener("click",()=>nav.classList.remove("open"));
document.querySelector("#year").textContent=new Date().getFullYear();


const backToTop=document.querySelector("#backToTop");
if(backToTop){backToTop.addEventListener("click",()=>{document.body.classList.remove("locked");window.scrollTo({top:0,left:0,behavior:"smooth"});});}
